//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int IdVentas { get; set; }
        public string CDBarras { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaVenta { get; set; }
        public int Cantidad { get; set; }
        public decimal CostoProducto { get; set; }
        public decimal Total { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
